from __future__ import annotations
from typing import Protocol


class Graphics(Protocol):
    def cls(self, col: int) -> None: ...
    def clip(self, x: int, y: int, w: int, h: int) -> None: ...
    def clip_reset(self) -> None: ...
    def pset(self, x: int, y: int, col: int) -> None: ...
    def line(self, x1: int, y1: int, x2: int, y2: int, col: int) -> None: ...
    def rect(self, x: int, y: int, w: int, h: int, col: int) -> None: ...
    def rectb(self, x: int, y: int, w: int, h: int, col: int) -> None: ...
    def circ(self, x: int, y: int, r: int, col: int) -> None: ...
    def circb(self, x: int, y: int, r: int, col: int) -> None: ...
    def elli(self, x: int, y: int, rx: int, ry: int, col: int) -> None: ...
    def ellib(self, x: int, y: int, rx: int, ry: int, col: int) -> None: ...
    def tri(self, x1: int, y1: int, x2: int, y2: int, x3: int, y3: int, col: int) -> None: ...
    def trib(self, x1: int, y1: int, x2: int, y2: int, x3: int, y3: int, col: int) -> None: ...
    def text(self, x: int, y: int, s: str, col: int) -> None: ...
