"""
Color constants for rendering.
This module provides standard color palette constants independent of any specific game engine.
Based on Pyxel's 16-color palette.
"""

# Pyxel's 16-color palette
COLOR_BLACK = 0
COLOR_NAVY = 1
COLOR_PURPLE = 2
COLOR_GREEN = 3
COLOR_BROWN = 4
COLOR_DARK_BLUE = 5
COLOR_LIGHT_BLUE = 6
COLOR_WHITE = 7
COLOR_RED = 8
COLOR_ORANGE = 9
COLOR_YELLOW = 10
COLOR_LIME = 11
COLOR_CYAN = 12
COLOR_GRAY = 13
COLOR_PINK = 14
COLOR_PEACH = 15

# Semantic aliases for common UI purposes
COLOR_BACKGROUND = COLOR_BLACK
COLOR_FOREGROUND = COLOR_WHITE
COLOR_PRIMARY = COLOR_LIGHT_BLUE
COLOR_SECONDARY = COLOR_PURPLE
COLOR_SUCCESS = COLOR_GREEN
COLOR_WARNING = COLOR_ORANGE
COLOR_ERROR = COLOR_RED
COLOR_INFO = COLOR_CYAN
COLOR_BORDER = COLOR_GRAY
COLOR_HIGHLIGHT = COLOR_YELLOW
COLOR_SELECTION = COLOR_CYAN

# All standard colors as a tuple (for iteration if needed)
STANDARD_COLORS = (
    COLOR_BLACK,
    COLOR_NAVY,
    COLOR_PURPLE,
    COLOR_GREEN,
    COLOR_BROWN,
    COLOR_DARK_BLUE,
    COLOR_LIGHT_BLUE,
    COLOR_WHITE,
    COLOR_RED,
    COLOR_ORANGE,
    COLOR_YELLOW,
    COLOR_LIME,
    COLOR_CYAN,
    COLOR_GRAY,
    COLOR_PINK,
    COLOR_PEACH,
)
